"""empty message

Revision ID: 7870dd8b8d57
Revises: b204d618230b
Create Date: 2021-07-19 13:37:28.545568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7870dd8b8d57'
down_revision = 'b204d618230b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paste', 'expiration_date')
    # ### end Alembic commands ###
