"""empty message

Revision ID: 8bb07a00e60b
Revises: 8d9b2e0d0385
Create Date: 2021-07-11 01:18:31.655112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb07a00e60b'
down_revision = '8d9b2e0d0385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'paste', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paste', type_='unique')
    # ### end Alembic commands ###
