"""empty message

Revision ID: b204d618230b
Revises: 8bb07a00e60b
Create Date: 2021-07-19 05:58:46.580902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b204d618230b'
down_revision = '8bb07a00e60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('language', sa.String(), nullable=True))
    op.drop_index('ix_paste_text', table_name='paste')
    op.drop_index('ix_paste_title', table_name='paste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_paste_title', 'paste', ['title'], unique=False)
    op.create_index('ix_paste_text', 'paste', ['text'], unique=False)
    op.drop_column('paste', 'language')
    # ### end Alembic commands ###
